### ISSUE TITLE
Wrong shape of array, conv2d_1_input

### ISSUE THREAD

**Issue by mrksbrg** [abhijeet3922/Object-recognition-CIFAR-10#1]
I got a ValueError on cifar10.py line 79 when running the code out of the box, please see the traceback below.

Running in a conda environment with the following versions:
Python 3.5.5
Tensorflow 1.9.0
Keras 2.2.0

```
Traceback (most recent call last):
  File "cifar10.py", line 79, in <module>
    model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=epochs, batch_size=32)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 955, in fit
    batch_size=batch_size)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 754, in _standardize_user_data
    exception_prefix='input')
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training_utils.py", line 136, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have shape (3, 32, 32) but got array with shape (32, 32, 3)
```

**Comment by mrksbrg** [comment]
Here is the complete print out. I notice a 'None' before the ValueError - does that indicate a problem?

```
(tensorflow) F:\Code\Object-recognition-CIFAR-10>python cifar10.py
Using TensorFlow backend.
(45000, 32, 32, 3)
2019-03-03 23:20:59.740270: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1392] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2019-03-03 23:20:59.752824: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2019-03-03 23:21:00.618936: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-03 23:21:00.625138: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0
2019-03-03 23:21:00.630302: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N
2019-03-03 23:21:00.634614: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8799 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_1 (Conv2D)            (None, 32, 32, 32)        896
_________________________________________________________________
dropout_1 (Dropout)          (None, 32, 32, 32)        0
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 32)        9248
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 16, 16)        0
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 64, 16, 16)        18496
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 64, 8, 8)          0
_________________________________________________________________
flatten_1 (Flatten)          (None, 4096)              0
_________________________________________________________________
dropout_2 (Dropout)          (None, 4096)              0
_________________________________________________________________
dense_1 (Dense)              (None, 512)               2097664
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130
=================================================================
Total params: 2,131,434
Trainable params: 2,131,434
Non-trainable params: 0
_________________________________________________________________
None
Traceback (most recent call last):
  File "cifar10.py", line 79, in <module>
    model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=epochs, batch_size=32)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 955, in fit
    batch_size=batch_size)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 754, in _standardize_user_data
    exception_prefix='input')
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training_utils.py", line 136, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have shape (3, 32, 32) but got array with shape (32, 32, 3)
```

**Comment by mrksbrg** [comment]
By the way, cifar10_90.py works like a charm!

**Comment by abhijeet3922** [comment]
Hey mrksbrg.
Sorry I am not getting time to fix this but hope you can figure out the error.
The shapes are miss-matching. Hope you can debug that (3,32,32) to (32,32,3).

**Comment by mrksbrg** [comment]
Thanks for the reply! I'm also not dependent on this fix, just wanted to report the issue. Cheers!
